FROM node:18-alpine
WORKDIR /app

COPY ./react-app/react-app/package.json .
COPY ./react-app/react-app/package-lock.json .

RUN npm install

COPY /react-app/react-app .

CMD ["npm", "run", "dev"]
EXPOSE 5173